### ISSUE TITLE
Crafting Recipe Error Crashes Game

### ISSUE THREAD

**Issue by DigitalVaporeon** [ThatPreston/Mermod-Fabric#3]
I tried to load up this mod in my modpack on 1.19.4, and it seems like all the modifier recipes crash the game as soon as you try to put them into a crafting grid. Crafting the necklaces themselves and dying them works fine with no issues, but trying to add any modifiers via the crafting grid (Glowing Pearl, Moon Rock, etc) immediately freezes up and then crashes the game as soon as you put both items in the crafting grid. Included 2 crash reports from 2 different modifier items but the issues seem to be the same in both of them.

I think this was trying to combine the necklace with the moon rock. This was the first crash
[crash-2023-03-29_15.02.50-server.txt](https://github.com/ThatPreston/Mermod-Fabric/files/11105175/crash-2023-03-29_15.02.50-server.txt)

This was the fourth crash from when I was testing each modifier, I think this was the tail gradient modifier.
[crash-2023-03-29_14.59.45-server.txt](https://github.com/ThatPreston/Mermod-Fabric/files/11105180/crash-2023-03-29_14.59.45-server.txt)

**Comment by ThatPreston** [comment]
Thanks for reporting! This is fixed now in 2.31.
